# site properties and page defaults
title: Collective Information Processing
subtitle: Romanczuk Lab
description: Welcome to the pages of the research group “Collective Information Processing” at the Institute for Theoretical Biology, Department of Biology, Humboldt Universität zu Berlin, associated with the Bernstein Center for Computational Neuroscience Berlin and the excellence cluster Science of Intelligence.
header: images/schwarm_romanczuk.png
footer: images/schwarm_romanczuk.png
proofer: false

# site social media and other links
links:
  email: pawel.romanczuk@hu-berlin.de
  orcid: 0000-0002-4733-998X
  google-scholar: CKoH18sAAAAJ
  github: promanczuk
  #twitter: promanczuk
  #youtube: promanczuk

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

# configure jekyll spaceship
jekyll-spaceship:
  mathjax-processor:
    src:
      - https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js
